// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjuLp4n2tjA9mlG_DdtxubqXjWSjeH_SI',
    appId: '1:366418920180:web:3dd6d8c709d6fe1f87d4a1',
    messagingSenderId: '366418920180',
    projectId: 'examen3-65374',
    authDomain: 'examen3-65374.firebaseapp.com',
    storageBucket: 'examen3-65374.appspot.com',
    measurementId: 'G-5GWT6T95D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARrOErZ8QTSKRV_Rw6_esyRqXbSfw3psc',
    appId: '1:366418920180:android:0997eafaa84da93787d4a1',
    messagingSenderId: '366418920180',
    projectId: 'examen3-65374',
    storageBucket: 'examen3-65374.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNcD23lecaDNNPx_k0cw25hLfWPSGJOlw',
    appId: '1:366418920180:ios:640d29844f3a909c87d4a1',
    messagingSenderId: '366418920180',
    projectId: 'examen3-65374',
    storageBucket: 'examen3-65374.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNcD23lecaDNNPx_k0cw25hLfWPSGJOlw',
    appId: '1:366418920180:ios:640d29844f3a909c87d4a1',
    messagingSenderId: '366418920180',
    projectId: 'examen3-65374',
    storageBucket: 'examen3-65374.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjuLp4n2tjA9mlG_DdtxubqXjWSjeH_SI',
    appId: '1:366418920180:web:3f8200a2733f5fda87d4a1',
    messagingSenderId: '366418920180',
    projectId: 'examen3-65374',
    authDomain: 'examen3-65374.firebaseapp.com',
    storageBucket: 'examen3-65374.appspot.com',
    measurementId: 'G-D9XS34MSX4',
  );
}
